// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TNSBackend.Data;

#nullable disable

namespace tns_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423161757_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TNSBackend.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Services"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Operations"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Customer Support"
                        });
                });

            modelBuilder.Entity("TNSBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FullName = "Benjamin Smith"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FullName = "Charlotte Brown"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            FullName = "Daniel Garcia"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            FullName = "Emma Martinez"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 6,
                            FullName = "Felix Wilson"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 7,
                            FullName = "Grace Hernandez"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 8,
                            FullName = "Henry Lopez"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 9,
                            FullName = "Isabella King"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 10,
                            FullName = "Jack White"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            FullName = "Katherine Moore"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            FullName = "Liam Walker"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            FullName = "Mia Robinson"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 4,
                            FullName = "Noah Scott"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 5,
                            FullName = "Olivia Hall"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 6,
                            FullName = "Peter Adams"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 7,
                            FullName = "Quinn Cooper"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 8,
                            FullName = "Rachel Evans"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 9,
                            FullName = "Samuel Carter"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 10,
                            FullName = "Taylor Reed"
                        });
                });

            modelBuilder.Entity("TNSBackend.Models.User", b =>
                {
                    b.HasOne("TNSBackend.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TNSBackend.Models.Department", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
